### PR TITLE
 Simplify wordquiz starting command

### PR DESCRIPTION
**Pull request by cubistplay**

### CODE REVIEW

**Comment by Fumire** [comment]
This case has been dismissed. 
∵ The difficulty cannot be set by chatting room

**Comment by Fumire** [comment]
@cubismic wants re-open PR.

**Comment by cubistplay** [comment]
I misunderstood the structure. I'll fix it

**Comment by cubistplay** [comment]
wordquize[] and wordDifficulty[] can be merged into a single data structure. 
But that takes lots of too much effort for now.
Should be done in code refactoring.

**Comment by Fumire** [comment]
This case has been resolved in different way as 627ba06b186ce91f04212363309048c33679c575

**Pull request closed without merging**
